name: Check org-bet code
on:
  pull_request:
  push:
jobs:
  test-melpa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.2
          - 28.2
          - 29.1
          - release-snapshot
        ignore_warnings:
          - true
        check:
          - melpa
        include:
          - emacs_version: snapshot
            check: melpa
            ignore_warnings: false
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Emacs Lisp check
        uses: leotaku/elisp-check@v1.3.1
        with:
          file: manifold.el
          check: ${{ matrix.check }}
          ignore_warnings: ${{ matrix.ignore_warnings }}
  test-builtin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3
          - 27.2
          - 28.2
          - 29.1
          - release-snapshot
          - snapshot
        ignore_warnings:
          - true
        check:
          - load-file
          - byte-compile
          - checkdoc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Emacs Lisp check
        uses: leotaku/elisp-check@v1.3.1
        with:
          file: manifold.el
          check: ${{ matrix.check }}
          ignore_warnings: ${{ matrix.ignore_warnings }}
